# Лабораторна робота №4
## Мета: отримати навички роботи із структурами для зберігання в Python (python, numpy, pandas, numpy array, dataframe, timeit)

#### Виконала студентка ФБ-23 Присєвок Оксана

In [1]:
import numpy as np
import os
import urllib.request
import zipfile
import timeit
import pandas as pd

In [2]:
def setup_folders(folder='lab4'):
    if not os.path.exists(folder):
        os.makedirs(folder)

def download_and_unzip_data(url, folder, file_name):
    file_path = os.path.join(folder, file_name)

    if not os.path.exists(file_path):
        print(f"Downloading {file_name}...")
        with urllib.request.urlopen(url) as response, open(file_path, 'wb') as out_file:
            out_file.write(response.read())
        print(f"{file_name} downloaded!")

        #unzip
        with zipfile.ZipFile(file_path, 'r') as zip_ref:
            zip_ref.extractall(folder)
        print(f"Extractes {file_name} to {folder}")

folder = 'lab4'
setup_folders(folder)

download_url = "https://archive.ics.uci.edu/static/public/235/individual+household+electric+power+consumption.zip"
file_name = 'household_power_consumption.zip'
download_and_unzip_data(download_url, folder, file_name)

In [3]:
def process_pandas_data(file_path):
    df = pd.read_csv(file_path, sep=";", na_values=['?'])
    df = df.dropna()
    df['DateTime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], format='%d/%m/%Y %H:%M:%S')
    df = df.drop(columns = ['Date', 'Time'])
    numeric_cols = ['Global_active_power', 'Global_reactive_power', 'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3']
    df[numeric_cols] = df[numeric_cols].astype(float)
    return df

file_path =os.path.join(folder, 'household_power_consumption.txt')
df = process_pandas_data(file_path)
print("Pandas dataframe processed successfuly")
df.head()

Pandas dataframe processed successfuly

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,DateTime
0,4.216,0.418,234.84,18.4,0.0,1.0,17.0,2006-12-16 17:24:00
1,5.360,0.436,233.63,23.0,0.0,1.0,16.0,2006-12-16 17:25:00
2,5.374,0.498,233.29,23.0,0.0,2.0,17.0,2006-12-16 17:26:00
3,5.388,0.502,233.74,23.0,0.0,1.0,17.0,2006-12-16 17:27:00
4,3.666,0.528,235.68,15.8,0.0,1.0,17.0,2006-12-16 17:28:00

In [4]:
start_time = timeit.default_timer()
high_power = df[df['Global_active_power'] > 5]
end_time = timeit.default_timer()
total_time_pd = end_time - start_time
print(f"Час виконання: {total_time_pd} секунд")
print("Домогосподарства з загальною активною потужністю більше 5 кВт:")
high_power.head()

Час виконання: 0.016860599999745318 секунд
Домогосподарства з загальною активною потужністю більше 5 кВт:

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,DateTime
1,5.360,0.436,233.63,23.0,0.0,1.0,16.0,2006-12-16 17:25:00
2,5.374,0.498,233.29,23.0,0.0,2.0,17.0,2006-12-16 17:26:00
3,5.388,0.502,233.74,23.0,0.0,1.0,17.0,2006-12-16 17:27:00
11,5.412,0.470,232.78,23.2,0.0,1.0,17.0,2006-12-16 17:35:00
12,5.224,0.478,232.99,22.4,0.0,1.0,16.0,2006-12-16 17:36:00

In [5]:
start_time = timeit.default_timer()
high_voltage = df[df['Voltage'] > 235]
end_time = timeit.default_timer()
total_time_pd = end_time - start_time
print(f"Час виконання: {total_time_pd} секунд")
print("Домогосподарства з напругою більше 235 В:")
high_voltage.head()

Час виконання: 0.16334990000041216 секунд
Домогосподарства з напругою більше 235 В:

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,DateTime
4,3.666,0.528,235.68,15.8,0.0,1.0,17.0,2006-12-16 17:28:00
5,3.520,0.522,235.02,15.0,0.0,2.0,17.0,2006-12-16 17:29:00
6,3.702,0.520,235.09,15.8,0.0,1.0,17.0,2006-12-16 17:30:00
7,3.700,0.520,235.22,15.8,0.0,1.0,17.0,2006-12-16 17:31:00
14,4.054,0.422,235.24,17.6,0.0,1.0,17.0,2006-12-16 17:38:00

In [6]:
start_time = timeit.default_timer()
current_range = df[(df['Global_intensity'] >= 19) & (df['Global_intensity'] <=20)]
condition_met = current_range[(current_range['Sub_metering_2'] > current_range['Sub_metering_3'])]
end_time = timeit.default_timer()
total_time_pd = end_time - start_time
print(f"Час виконання: {total_time_pd} секунд")
print("Домогосподарства з силою струму 19-20 А, де пральна машина та холодильник споживають більше:")
condition_met.head()

Час виконання: 0.0200832000000446 секунд
Домогосподарства з силою струму 19-20 А, де пральна машина та холодильник споживають більше:

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,DateTime
45,4.464,0.136,234.66,19.0,0.0,37.0,16.0,2006-12-16 18:09:00
460,4.582,0.258,238.08,19.6,0.0,13.0,0.0,2006-12-17 01:04:00
464,4.618,0.104,239.61,19.6,0.0,27.0,0.0,2006-12-17 01:08:00
475,4.636,0.140,237.37,19.4,0.0,36.0,0.0,2006-12-17 01:19:00
476,4.634,0.152,237.17,19.4,0.0,35.0,0.0,2006-12-17 01:20:00

In [7]:
start_time = timeit.default_timer()
random_sample = df.sample(n=500000, replace=False)
mean_consumption = random_sample[['Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3']].mean()
end_time = timeit.default_timer()
total_time_pd = end_time - start_time
print(f"Час виконання: {total_time_pd} секунд")
print("Середні величини усіх трьох груп споживання електроенергії:")
mean_consumption

Час виконання: 0.20380150000028152 секунд
Середні величини усіх трьох груп споживання електроенергії:

Sub_metering_1    1.119830
Sub_metering_2    1.306628
Sub_metering_3    6.481662
dtype: float64

In [8]:
start_time = timeit.default_timer()
evening_high_usage = df[(df['DateTime'].dt.hour >=18) & (df['Global_active_power'] >6)]
group2_largest = evening_high_usage[evening_high_usage['Sub_metering_2'] > evening_high_usage['Sub_metering_1']]
first_half_selection = group2_largest.iloc[:len(group2_largest)//2:3]
second_half_selection = group2_largest.iloc[:len(group2_largest)//2:4]
end_time = timeit.default_timer()
total_time_pd = end_time - start_time
print(f"Час виконання: {total_time_pd} секунд")
combined_df = pd.concat([first_half_selection, second_half_selection])
print("Домогосподарства, які після 18:00 споживають понад 6 кВт за хвилину в середньому:")
combined_df.head()

Час виконання: 0.24272019999989425 секунд
Домогосподарства, які після 18:00 споживають понад 6 кВт за хвилину в середньому:

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,DateTime
41,6.052,0.192,232.93,26.2,0.0,37.0,17.0,2006-12-16 18:05:00
44,6.308,0.116,232.25,27.0,0.0,36.0,17.0,2006-12-16 18:08:00
17494,6.386,0.374,236.63,27.0,1.0,36.0,17.0,2006-12-28 20:58:00
17498,8.088,0.262,235.50,34.4,1.0,72.0,17.0,2006-12-28 21:02:00
17501,7.230,0.152,235.22,30.6,1.0,73.0,17.0,2006-12-28 21:05:00

In [9]:
def load_data(file_path):
    data_array = np.genfromtxt(file_path, delimiter=';', skip_header=1, dtype=None, encoding='utf-8')
    string_data_array = np.array([tuple(str(item) for item in row) for row in data_array])
    mask = np.all((string_data_array != '?'), axis=1)
    data = string_data_array[mask]
    float_cols = data[:, 2:8].astype(float)
    data = np.hstack((data[:, :2], float_cols, data[:, 8:]))
    return data

folder = 'lab4'
file_path = os.path.join(folder, 'household_power_consumption.txt')
np_data = load_data(file_path)
print("Numpy array processed successfully.")
print(np_data[:5])

Numpy array processed successfully.
[['16/12/2006' '17:24:00' '4.216' '0.418' '234.84' '18.4' '0.0' '1.0'
  '17.0']
 ['16/12/2006' '17:25:00' '5.36' '0.436' '233.63' '23.0' '0.0' '1.0'
  '16.0']
 ['16/12/2006' '17:26:00' '5.374' '0.498' '233.29' '23.0' '0.0' '2.0'
  '17.0']
 ['16/12/2006' '17:27:00' '5.388' '0.502' '233.74' '23.0' '0.0' '1.0'
  '17.0']
 ['16/12/2006' '17:28:00' '3.666' '0.528' '235.68' '15.8' '0.0' '1.0'
  '17.0']]

In [11]:
mask = np_data[:, 2].astype(float)>5
selected_rows = np_data[mask]
time_np = timeit.timeit(lambda: selected_rows, number=1)
print(f"Час виконання для NumPy: {time_np} секунд")
print("Домогосподарства з загальною активною потужністю більше 5 кВт:")
print(selected_rows)

Час виконання для NumPy: 2.099999619531445e-06 секунд
Домогосподарства з загальною активною потужністю більше 5 кВт:
[['16/12/2006' '17:25:00' '5.36' ... '0.0' '1.0' '16.0']
 ['16/12/2006' '17:26:00' '5.374' ... '0.0' '2.0' '17.0']
 ['16/12/2006' '17:27:00' '5.388' ... '0.0' '1.0' '17.0']
 ...
 ['24/11/2010' '07:50:00' '5.172' ... '0.0' '38.0' '17.0']
 ['24/11/2010' '07:51:00' '5.75' ... '0.0' '39.0' '17.0']
 ['25/11/2010' '07:21:00' '5.074' ... '1.0' '2.0' '18.0']]

In [18]:
mask = np_data[:, 4].astype(float)>235
selected_rows = np_data[mask]
time_np = timeit.timeit(lambda: selected_rows, number=1)
print(f"Час виконання для NumPy: {time_np} секунд")
print("Домогосподарства з напругою більше 235 В:")
print(selected_rows)

Час виконання для NumPy: 1.4200000805431046e-05 секунд
Домогосподарства з напругою більше 235 В:
[['16/12/2006' '17:28:00' '3.666' ... '0.0' '1.0' '17.0']
 ['16/12/2006' '17:29:00' '3.52' ... '0.0' '2.0' '17.0']
 ['16/12/2006' '17:30:00' '3.702' ... '0.0' '1.0' '17.0']
 ...
 ['26/11/2010' '21:00:00' '0.938' ... '0.0' '0.0' '0.0']
 ['26/11/2010' '21:01:00' '0.934' ... '0.0' '0.0' '0.0']
 ['26/11/2010' '21:02:00' '0.932' ... '0.0' '0.0' '0.0']]

In [16]:
start_time = timeit.default_timer()
mask = (np_data[:, 5].astype(float) >=19) & (np_data[:, 5].astype(float) <=20)
current_filtered = np_data[mask]

mask_appliance = current_filtered[:, 6].astype(float) > current_filtered[:, 7].astype(float)
selected_rows = current_filtered[mask_appliance]
end_time = timeit.default_timer()
total_time_np = end_time - start_time

print(f"Час виконання для NumPy: {total_time_np} секунд")
print("Домогосподарства з силою струму 19-20 А, де пральна машина та холодильник споживають більше:")
print(selected_rows)

Час виконання для NumPy: 5.050749500000165 секунд
Домогосподарства з силою струму 19-20 А, де пральна машина та холодильник споживають більше:
[['17/12/2006' '15:28:00' '4.502' ... '1.0' '0.0' '17.0']
 ['19/12/2006' '09:04:00' '4.674' ... '38.0' '18.0' '17.0']
 ['21/12/2006' '19:53:00' '4.454' ... '38.0' '0.0' '0.0']
 ...
 ['23/11/2010' '18:58:00' '4.618' ... '47.0' '0.0' '0.0']
 ['23/11/2010' '18:59:00' '4.586' ... '46.0' '0.0' '0.0']
 ['23/11/2010' '19:00:00' '4.628' ... '47.0' '0.0' '0.0']]

In [17]:
start_time = timeit.default_timer()
random_indices = np.random.choice(np_data.shape[0], size=500000, replace=False)

selected_rows = np_data[random_indices]
averange_consumptions = np.mean(selected_rows[:, 6:9].astype(float), axis=0)

end_time = timeit.default_timer()
total_time_np = end_time - start_time
print(f"Час виконання для NumPy: {total_time_np} секунд")
print("Середні величини усіх трьох груп споживання електроенергії:")
print("Sub_metering_1: ", averange_consumptions[0], "Sub_metering_2: ", averange_consumptions[1], "Sub_metering_3: ", averange_consumptions[2])

Час виконання для NumPy: 2.6988068000000567 секунд
Середні величини усіх трьох груп споживання електроенергії:
Sub_metering_1:  1.126518 Sub_metering_2:  1.291536 Sub_metering_3:  6.43736

In [22]:
start_time = timeit.default_timer()
mask_time = np_data[:, 1].astype(str) > '18:00:00'
mask_power = np_data[:, 2].astype(float) > 6
selected_rows = np_data[mask_time & mask_power]
mask_group = (selected_rows[:, 7].astype(float) > selected_rows[:, 6].astype(float)) & (selected_rows[:, 7].astype(float) > selected_rows[:, 8].astype(float))
filtered_rows = selected_rows[mask_group]

first_half = filtered_rows[:len(filtered_rows)//2]
selected_first_half = first_half[::3]

second_half = filtered_rows[len(filtered_rows)//2:]
selected_second_half = second_half[::4]

final_selection = np.vstack((selected_first_half, selected_second_half))

end_time = timeit.default_timer()
total_time_np = end_time - start_time


print(f"Час виконання для NumPy: {total_time_np} секунд")
print("Домогосподарства, які після 18:00 споживають понад 6 кВт за хвилину в середньому:")
print(final_selection)

Час виконання для NumPy: 3.0598624000012933 секунд
Домогосподарства, які після 18:00 споживають понад 6 кВт за хвилину в середньому:
[['16/12/2006' '18:05:00' '6.052' ... '0.0' '37.0' '17.0']
 ['16/12/2006' '18:08:00' '6.308' ... '0.0' '36.0' '17.0']
 ['28/12/2006' '20:58:00' '6.386' ... '1.0' '36.0' '17.0']
 ...
 ['20/11/2010' '18:39:00' '6.362' ... '16.0' '35.0' '16.0']
 ['20/11/2010' '18:43:00' '6.324' ... '14.0' '35.0' '17.0']
 ['20/11/2010' '18:49:00' '6.21' ... '21.0' '34.0' '17.0']]